name: 米游原

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # cron表达式，Actions时区是UTC+8时间，所以要往前推8个小时

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # 设置服务器时区为东八区 
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '16.3.0'
      
      - name: Do sign
        env:
          SIGN_TARGET_COOKIE_YUU: ${{ secrets.YUU_COOKIE }}
        run: npm run daily-sign
